### ISSUE TITLE
Opinion Mining link not working

### ISSUE THREAD

**Issue by diazgilberto** [dav009/awesome-spanish-nlp#3]
The following link is not working...

`Opinion Mining - User reviews on Cars, Hotels, Washing machines, Books, Cell phones, Music..`

Do you have a working link?

**Comment by dav009** [comment]
it seems this is the new link: 
https://www.sfu.ca/~mtaboada/SFU_Review_Corpus.html
gonna update it 🙇

**Comment by diazgilberto** [comment]
Thank you!
Do you have knowledge of a corpus of complaints in Spanish? Could be banks, amazon, etc.
